# Generated by Django 5.0.6 on 2024-05-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_change_profile', 'Can change Profile')]},
        ),
    ]
