# Generated by Django 5.0.6 on 2024-05-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_change_profile', 'Can change Profile'), ('access_dashboard', 'Can access dashboard')]},
        ),
    ]
